vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("user.options")
--require("user.plugins")
require("user.lualine")
require("user.telescope")
--require("user.appearance")
require("user.appearance-tokyo")
require("user.lsp_installer")
require("user.cmp")
--require("user.null_ls")
require("user.lsp")
require("user.luasnip")
require("user.treesitter")
require("user.vimtex")
require("user.keymaps")
require("user.blankline")
require("user.dashboard")
require("user.githubpreview")
--require("user.nvim_tree")
